In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [2]:
# Get the column names

# the official website for Taiwanese Dictionary
url = 'https://sutian.moe.edu.tw/zh-hant/huliok/106/'
page = requests.get(url)
soup = BeautifulSoup(page.text, 'html.parser') 
table = soup.find_all('table')

# Find all <th> elements (table headers)
titles = soup.find_all('th')  

# Extract text from the <th> elements
table_titles = [title.text.strip() for title in titles]

# Create a DataFrame with the first four titles as headers
headers = table_titles[:4]
df = pd.DataFrame(columns=headers)

# Add an additional 'href' column for audio URL
df['href'] = None

In [3]:
# function to scrap one page
def scrapSinglePage(page):
    pageNum = str(page)
    url = 'https://sutian.moe.edu.tw/zh-hant/huliok/106/?iahbe=' + pageNum # concat the URL and page number
    curPage = requests.get(url)
    soup = BeautifulSoup(curPage.text, 'html')
    table = soup.find_all('table')

    
    for row in table[:-1]:
        # last row of table is not a valid row 
        row_data = row.find_all('td')
        a_tag  = row.find('a')
        href_value = a_tag['href']
        individual_row_data = []
        for data in row_data:
            # Strip and clean the text
            cleaned_text = data.text.strip().replace('\n', '').replace('\t', '').replace('\r', '')
            # Find the first period and keep everything up to and including it
            period_index = cleaned_text.find('.')
            
            if period_index != -1:
                cleaned_text = cleaned_text[:period_index + 1]
            
        
            individual_row_data.append(cleaned_text)

        # The URL for audio
        individual_row_data.append("https://sutian.moe.edu.tw/" + href_value)
        length = len(df)
        df.loc[length] = individual_row_data

In [4]:
# Scrap all 20 pages
for i in range(3):
    scrapSinglePage(i)
df

,序號,詞目,音讀,釋義,href
0,1,鴨仔聽雷。,Ah-á thiann luî.,指鴨子聽到雷聲，並不知道是怎麼回事。比喻一個人對所接收的訊息無法理解。比喻一個人對所接收的訊...,https://sutian.moe.edu.tw//zh-hant/su/27204/
1,2,愛拚才會贏。,Ài piànn tsiah ē iânn.,要努力才會贏。比喻唯有努力奮鬥，才能克服困難，成就一番事業。,https://sutian.moe.edu.tw//zh-hant/su/27161/
2,3,愛媠毋驚流鼻水。,Ài-suí m̄ kiann lâu phīnn-tsuí.,為了展示自己姣好的身材，天氣再冷，寧可挨寒受凍，也不願多穿衣服。常用以揶揄女性愛美，寧可付出...,https://sutian.moe.edu.tw//zh-hant/su/27162/
3,4,暗頭仔食西瓜，半暝仔反症。,"Àm-thâu-á tsia̍h si-kue, puànn-mê-á huán-tsìng.",傍晚吃西瓜，半夜症狀急遽變化。指中途變卦，出爾反爾。,https://sutian.moe.edu.tw//zh-hant/su/29615/
4,5,暗頓減食一口，活甲九十九。,"Àm-tǹg kiám tsia̍h tsi̍t kháu, ua̍h kah káu-ts...",晚餐少吃一口，活到九十九。說明晚餐的食用量少一點，有益身體健康。,https://sutian.moe.edu.tw//zh-hant/su/27164/
5,6,翁仔某是相欠債。,Ang-á-bóo sī sio-khiàm-tsè.,今世有緣結為夫妻，乃因前世因果，互相欠債所致。夫妻意見不合相互爭吵時，常用這句話來勸雙方姻緣...,https://sutian.moe.edu.tw//zh-hant/su/27093/
6,7,翁某若仝心，烏塗變成金。,"Ang-bóo nā kāng-sim, oo-thôo piàn-sîng kim.",夫妻若同心協力，沒有價值的黑土都能變成高價值的東西。比喻夫妻和諧，一起努力，任何事都可成就。,https://sutian.moe.edu.tw//zh-hant/su/27094/
7,8,尪姨順話尾，假童害眾人。,"Ang-î sūn uē-bué, ké tâng hāi tsìng-lâng.",靈媒會順著對方的心意說話，假冒之乩童故意裝神弄鬼來欺騙人。此指靈媒、乩童借揣摩情況來決定說話...,https://sutian.moe.edu.tw//zh-hant/su/27026/
8,9,翁親某親，老婆仔拋捙輪。,"Ang tshin bóo tshin, lāu-pô-á pha-tshia-lin.",夫妻恩愛，老婆婆翻筋斗也不管。「老婆仔」是指年邁的母親，「拋捙輪」是翻筋斗，這裡指老母親跌倒...,https://sutian.moe.edu.tw//zh-hant/su/27095/
9,10,紅媠，烏大範。,"Âng suí, oo tuā-pān.",紅色美麗，黑色大方。形容人衣著色彩，紅色顯得鮮豔亮麗，黑色呈現高貴大方，有氣質、有風味。也可...,https://sutian.moe.edu.tw//zh-hant/su/27061/
10,11,肉欲予人食，骨毋予人齧。,"Bah beh hōo lâng tsia̍h, kut m̄ hōo lâng khè.",肉還可以讓人家吃，骨頭千萬不可被人家啃。指被欺負，委曲求全，但忍耐有一定的限度，不能被欺負太...,https://sutian.moe.edu.tw//zh-hant/su/29014/
11,12,䆀猴𠢕欠數。,Bái-kâu gâu khiàm-siàu.,難纏的客人愛賒帳。形容人外型不佳又愛賒帳。,https://sutian.moe.edu.tw//zh-hant/su/27217/
12,13,目睭花花，匏仔看做菜瓜。,"Ba̍k-tsiu hue-hue, pû-á khuànn-tsò tshài-kue.",眼睛看不清楚，瓠瓜看成絲瓜。嘲笑別人一時恍神，把形狀相近的物品看成別的東西。,https://sutian.moe.edu.tw//zh-hant/su/26983/
13,14,目睭看懸，無看低。,"Ba̍k-tsiu khuànn-kuân, bô khuànn-kē.",眼睛長在頭頂上，看上不看下。形容人走路不看路。引申為人勢利，看不起身分較低的人。,https://sutian.moe.edu.tw//zh-hant/su/26986/
14,15,目睭看佇粿，跤踏著火。,"Ba̍k-tsiu khuànn tī kué, kha ta̍h-tio̍h hué.",眼睛看著糕品，腳踩到火。用來勸人做事不要只顧當前的好處，而忘了週遭的危險，以免身陷險境而不知。,https://sutian.moe.edu.tw//zh-hant/su/26985/
15,16,目睭金金人傷重。,Ba̍k-tsiu kim-kim lâng siong-tiōng.,眼睛睜大，病情嚴重。形容人病得很嚴重，只能張大眼睛，無法動彈；也用來比喻遇到事情束手無策，只...,https://sutian.moe.edu.tw//zh-hant/su/26984/
16,17,目睭掛斗概，看人物就愛。,"Ba̍k-tsiu kuà táu-kài, khuànn lâng mi̍h tō ài.",眼睛掛著平斗的木概，看到別人的東西就想要。用來形容人過於貪心。以前用「斗」來測量穀物豆類等東...,https://sutian.moe.edu.tw//zh-hant/su/26987/
17,18,慢牛厚屎尿。,Bān gû kāu-sái-jiō.,行動遲緩的牛屎尿多。比喻懶惰的人做事不乾脆，常找藉口逃避或延遲該盡的責任。,https://sutian.moe.edu.tw//zh-hant/su/27183/
18,19,萬事起頭難。,Bān-sū khí-thâu lân.,一切事情開頭階段都很困難。意指事情剛開始的時候，都比較困難，只要不放棄，繼續做，久了就會順手...,https://sutian.moe.edu.tw//zh-hant/su/27169/
19,20,買賣算分，相請無論。,"Bé-bē sǹg hun, sio-tshiánn bô lūn.",做生意就得把帳目算個清楚，至於請客吃飯，則無需計較。說明生意與交情的界線理應分明。,https://sutian.moe.edu.tw//zh-hant/su/27152/
20,21,馬四跤也會著觸。,Bé sì kha iā ē tio̍h-tak.,馬有四條腿，也會因失蹄而跌倒；表示再聰明能幹的人，都會有失意、落魄之時。,https://sutian.moe.edu.tw//zh-hant/su/29027/
21,22,買田愛揀好田底，娶某愛揀好娘嬭。,"Bé tshân ài kíng hó tshân té, tshuā-bóo ài kín...",買田地，要慎選土質好的田地；娶老婆，要先觀察女方母親之行為舉止。意即有其母必有其女，用來說明...,https://sutian.moe.edu.tw//zh-hant/su/27150/
22,23,買厝，買厝邊。,"Bé tshù, bé tshù-pinn.",買房子要慎選好鄰居。強調選擇住家時，鄰居的好壞至關重要。,https://sutian.moe.edu.tw//zh-hant/su/27151/
23,24,袂曉剃頭，拄著鬍鬚。,"Bē-hiáu thì-thâu, tú-tio̍h hôo-tshiu.",不會理髮，遇到大鬍子。理髮師技術還不夠純熟，首次上場就遇到一個大鬍子的客人，以致於手忙腳亂，...,https://sutian.moe.edu.tw//zh-hant/su/27098/
24,25,袂生，牽拖厝邊。,"Bē sinn, khan-thua tshù-pinn.",自己無法生育，卻怪罪鄰居。是用來嘲諷出了問題不自我檢討，卻只會卸責給他人。俗諺多數前後句押韻...,https://sutian.moe.edu.tw//zh-hant/su/29039/
25,26,賣茶講茶芳，賣花講花紅。,"Bē tê kóng tê phang, bē hue kóng hue âng.",賣茶葉的人強調自己賣的茶葉有多香；賣花的人強調自己賣的花顏色有多麼的鮮豔。比喻為了要把自己的...,https://sutian.moe.edu.tw//zh-hant/su/27194/
26,27,欲好額等後世，欲做官學做戲。,"Beh hó-gia̍h tán āu-sì, beh tsò-kuann o̍h tsò-hì.",如果想發財就等下輩子，如果想當官，去戲班子演戲就能過乾癮。諷刺人此生再無致富與升官的機會，有...,https://sutian.moe.edu.tw//zh-hant/su/27115/
27,28,欲哭無目屎。,Beh khàu bô ba̍k-sái.,想哭卻掉不下淚來。比喻極度哀傷、悲痛。,https://sutian.moe.edu.tw//zh-hant/su/29617/
28,29,欲食胡蠅，家己欱。,"Beh tsia̍h hôo-sîn, ka-kī hap.",想吃蒼蠅得自己去捕捉。引申為凡事得自食其力，不可依賴別人。,https://sutian.moe.edu.tw//zh-hant/su/29064/
29,30,無米有舂臼，無囝抱新婦。,"Bô bí ū tsing-khū, bô kiánn phō sin-pū.",沒有米卻有搗米的臼；沒有兒子領養一個童養媳。形容人只會做白日夢，不切實際。,https://sutian.moe.edu.tw//zh-hant/su/27140/
30,31,無牛駛馬。,Bô gû sái bé.,沒有牛只能用馬匹來替代。形容退而求其次，暫且代用的無奈。,https://sutian.moe.edu.tw//zh-hant/su/27139/
31,32,無魚，蝦嘛好。,"Bô hî, hê mā hó.",捉不到魚，捉到蝦子也好。比喻退而求其次，聊勝於無。,https://sutian.moe.edu.tw//zh-hant/su/27144/
32,33,無彼號尻川，想欲食彼號瀉藥。,"Bô hit-lō kha-tshng, siūnn-beh tsia̍h hit-lō s...",沒有那種屁股，想吃那種瀉藥。形容人沒有那種能耐，卻妄想做那種事。比喻一個人自不量力。,https://sutian.moe.edu.tw//zh-hant/su/27141/
33,34,無風無搖，倒大樹。,"Bô-hong-bô-iô, tó tuā-tshiū.",沒有絲毫的風，大樹竟然倒了。形容毫無徵兆，發生了意外的大事。,https://sutian.moe.edu.tw//zh-hant/su/28975/
34,35,無日毋知晝，無鬚毋知老。,"Bô ji̍t m̄ tsai tàu, bô tshiu m̄ tsai lāu.",沒出太陽，不知已經到中午了；沒留鬍子，不易察覺人已老邁。比喻光陰易逝，很容易在不知不覺中荒廢。,https://sutian.moe.edu.tw//zh-hant/su/27137/
35,36,無枷夯交椅。,Bô kê giâ kau-í.,沒有枷鎖等刑具可披枷帶鎖，竟然將太師椅扛在身上。比喻自找麻煩，庸人自擾。,https://sutian.moe.edu.tw//zh-hant/su/27142/
36,37,無禁無忌，食百二。,"Bô-kìm-bô-khī, tsia̍h pah-jī.",形容人百無禁忌，毫無忌諱，便能長壽活到一百二十歲。通常是觸碰禁忌者用來自我安慰的說法。,https://sutian.moe.edu.tw//zh-hant/su/27145/
37,38,無毛雞假大格。,Bô môo ke ké tuā-keh.,發育不良羽毛稀疏的雞假冒成體格高大。比喻一個人明明沒錢還裝闊；或指人明明沒有才能，還裝出很有...,https://sutian.moe.edu.tw//zh-hant/su/27138/
38,39,無通生食，哪有通曝乾。,"Bô thang tshenn tsia̍h, ná ū thang pha̍k-kuann.",生吃都不夠，哪能晒成乾？比喻數量不足，不可能有多餘的留下來。也指個人或家計窘困，沒有餘錢作額...,https://sutian.moe.edu.tw//zh-hant/su/27143/
39,40,罔趁較袂散。,Bóng thàn khah bē sàn.,多少賺一點，才不致於陷入窮困。說明即使利潤非常小，也應積極賺取。,https://sutian.moe.edu.tw//zh-hant/su/27037/

In [5]:
# Update header to English
df.columns = ['id', 'phrases', 'pronounciation', 'definition', 'audiourl']
df

,id,phrases,pronounciation,definition,audiourl
0,1,鴨仔聽雷。,Ah-á thiann luî.,指鴨子聽到雷聲，並不知道是怎麼回事。比喻一個人對所接收的訊息無法理解。比喻一個人對所接收的訊...,https://sutian.moe.edu.tw//zh-hant/su/27204/
1,2,愛拚才會贏。,Ài piànn tsiah ē iânn.,要努力才會贏。比喻唯有努力奮鬥，才能克服困難，成就一番事業。,https://sutian.moe.edu.tw//zh-hant/su/27161/
2,3,愛媠毋驚流鼻水。,Ài-suí m̄ kiann lâu phīnn-tsuí.,為了展示自己姣好的身材，天氣再冷，寧可挨寒受凍，也不願多穿衣服。常用以揶揄女性愛美，寧可付出...,https://sutian.moe.edu.tw//zh-hant/su/27162/
3,4,暗頭仔食西瓜，半暝仔反症。,"Àm-thâu-á tsia̍h si-kue, puànn-mê-á huán-tsìng.",傍晚吃西瓜，半夜症狀急遽變化。指中途變卦，出爾反爾。,https://sutian.moe.edu.tw//zh-hant/su/29615/
4,5,暗頓減食一口，活甲九十九。,"Àm-tǹg kiám tsia̍h tsi̍t kháu, ua̍h kah káu-ts...",晚餐少吃一口，活到九十九。說明晚餐的食用量少一點，有益身體健康。,https://sutian.moe.edu.tw//zh-hant/su/27164/
5,6,翁仔某是相欠債。,Ang-á-bóo sī sio-khiàm-tsè.,今世有緣結為夫妻，乃因前世因果，互相欠債所致。夫妻意見不合相互爭吵時，常用這句話來勸雙方姻緣...,https://sutian.moe.edu.tw//zh-hant/su/27093/
6,7,翁某若仝心，烏塗變成金。,"Ang-bóo nā kāng-sim, oo-thôo piàn-sîng kim.",夫妻若同心協力，沒有價值的黑土都能變成高價值的東西。比喻夫妻和諧，一起努力，任何事都可成就。,https://sutian.moe.edu.tw//zh-hant/su/27094/
7,8,尪姨順話尾，假童害眾人。,"Ang-î sūn uē-bué, ké tâng hāi tsìng-lâng.",靈媒會順著對方的心意說話，假冒之乩童故意裝神弄鬼來欺騙人。此指靈媒、乩童借揣摩情況來決定說話...,https://sutian.moe.edu.tw//zh-hant/su/27026/
8,9,翁親某親，老婆仔拋捙輪。,"Ang tshin bóo tshin, lāu-pô-á pha-tshia-lin.",夫妻恩愛，老婆婆翻筋斗也不管。「老婆仔」是指年邁的母親，「拋捙輪」是翻筋斗，這裡指老母親跌倒...,https://sutian.moe.edu.tw//zh-hant/su/27095/
9,10,紅媠，烏大範。,"Âng suí, oo tuā-pān.",紅色美麗，黑色大方。形容人衣著色彩，紅色顯得鮮豔亮麗，黑色呈現高貴大方，有氣質、有風味。也可...,https://sutian.moe.edu.tw//zh-hant/su/27061/
10,11,肉欲予人食，骨毋予人齧。,"Bah beh hōo lâng tsia̍h, kut m̄ hōo lâng khè.",肉還可以讓人家吃，骨頭千萬不可被人家啃。指被欺負，委曲求全，但忍耐有一定的限度，不能被欺負太...,https://sutian.moe.edu.tw//zh-hant/su/29014/
11,12,䆀猴𠢕欠數。,Bái-kâu gâu khiàm-siàu.,難纏的客人愛賒帳。形容人外型不佳又愛賒帳。,https://sutian.moe.edu.tw//zh-hant/su/27217/
12,13,目睭花花，匏仔看做菜瓜。,"Ba̍k-tsiu hue-hue, pû-á khuànn-tsò tshài-kue.",眼睛看不清楚，瓠瓜看成絲瓜。嘲笑別人一時恍神，把形狀相近的物品看成別的東西。,https://sutian.moe.edu.tw//zh-hant/su/26983/
13,14,目睭看懸，無看低。,"Ba̍k-tsiu khuànn-kuân, bô khuànn-kē.",眼睛長在頭頂上，看上不看下。形容人走路不看路。引申為人勢利，看不起身分較低的人。,https://sutian.moe.edu.tw//zh-hant/su/26986/
14,15,目睭看佇粿，跤踏著火。,"Ba̍k-tsiu khuànn tī kué, kha ta̍h-tio̍h hué.",眼睛看著糕品，腳踩到火。用來勸人做事不要只顧當前的好處，而忘了週遭的危險，以免身陷險境而不知。,https://sutian.moe.edu.tw//zh-hant/su/26985/
15,16,目睭金金人傷重。,Ba̍k-tsiu kim-kim lâng siong-tiōng.,眼睛睜大，病情嚴重。形容人病得很嚴重，只能張大眼睛，無法動彈；也用來比喻遇到事情束手無策，只...,https://sutian.moe.edu.tw//zh-hant/su/26984/
16,17,目睭掛斗概，看人物就愛。,"Ba̍k-tsiu kuà táu-kài, khuànn lâng mi̍h tō ài.",眼睛掛著平斗的木概，看到別人的東西就想要。用來形容人過於貪心。以前用「斗」來測量穀物豆類等東...,https://sutian.moe.edu.tw//zh-hant/su/26987/
17,18,慢牛厚屎尿。,Bān gû kāu-sái-jiō.,行動遲緩的牛屎尿多。比喻懶惰的人做事不乾脆，常找藉口逃避或延遲該盡的責任。,https://sutian.moe.edu.tw//zh-hant/su/27183/
18,19,萬事起頭難。,Bān-sū khí-thâu lân.,一切事情開頭階段都很困難。意指事情剛開始的時候，都比較困難，只要不放棄，繼續做，久了就會順手...,https://sutian.moe.edu.tw//zh-hant/su/27169/
19,20,買賣算分，相請無論。,"Bé-bē sǹg hun, sio-tshiánn bô lūn.",做生意就得把帳目算個清楚，至於請客吃飯，則無需計較。說明生意與交情的界線理應分明。,https://sutian.moe.edu.tw//zh-hant/su/27152/
20,21,馬四跤也會著觸。,Bé sì kha iā ē tio̍h-tak.,馬有四條腿，也會因失蹄而跌倒；表示再聰明能幹的人，都會有失意、落魄之時。,https://sutian.moe.edu.tw//zh-hant/su/29027/
21,22,買田愛揀好田底，娶某愛揀好娘嬭。,"Bé tshân ài kíng hó tshân té, tshuā-bóo ài kín...",買田地，要慎選土質好的田地；娶老婆，要先觀察女方母親之行為舉止。意即有其母必有其女，用來說明...,https://sutian.moe.edu.tw//zh-hant/su/27150/
22,23,買厝，買厝邊。,"Bé tshù, bé tshù-pinn.",買房子要慎選好鄰居。強調選擇住家時，鄰居的好壞至關重要。,https://sutian.moe.edu.tw//zh-hant/su/27151/
23,24,袂曉剃頭，拄著鬍鬚。,"Bē-hiáu thì-thâu, tú-tio̍h hôo-tshiu.",不會理髮，遇到大鬍子。理髮師技術還不夠純熟，首次上場就遇到一個大鬍子的客人，以致於手忙腳亂，...,https://sutian.moe.edu.tw//zh-hant/su/27098/
24,25,袂生，牽拖厝邊。,"Bē sinn, khan-thua tshù-pinn.",自己無法生育，卻怪罪鄰居。是用來嘲諷出了問題不自我檢討，卻只會卸責給他人。俗諺多數前後句押韻...,https://sutian.moe.edu.tw//zh-hant/su/29039/
25,26,賣茶講茶芳，賣花講花紅。,"Bē tê kóng tê phang, bē hue kóng hue âng.",賣茶葉的人強調自己賣的茶葉有多香；賣花的人強調自己賣的花顏色有多麼的鮮豔。比喻為了要把自己的...,https://sutian.moe.edu.tw//zh-hant/su/27194/
26,27,欲好額等後世，欲做官學做戲。,"Beh hó-gia̍h tán āu-sì, beh tsò-kuann o̍h tsò-hì.",如果想發財就等下輩子，如果想當官，去戲班子演戲就能過乾癮。諷刺人此生再無致富與升官的機會，有...,https://sutian.moe.edu.tw//zh-hant/su/27115/
27,28,欲哭無目屎。,Beh khàu bô ba̍k-sái.,想哭卻掉不下淚來。比喻極度哀傷、悲痛。,https://sutian.moe.edu.tw//zh-hant/su/29617/
28,29,欲食胡蠅，家己欱。,"Beh tsia̍h hôo-sîn, ka-kī hap.",想吃蒼蠅得自己去捕捉。引申為凡事得自食其力，不可依賴別人。,https://sutian.moe.edu.tw//zh-hant/su/29064/
29,30,無米有舂臼，無囝抱新婦。,"Bô bí ū tsing-khū, bô kiánn phō sin-pū.",沒有米卻有搗米的臼；沒有兒子領養一個童養媳。形容人只會做白日夢，不切實際。,https://sutian.moe.edu.tw//zh-hant/su/27140/
30,31,無牛駛馬。,Bô gû sái bé.,沒有牛只能用馬匹來替代。形容退而求其次，暫且代用的無奈。,https://sutian.moe.edu.tw//zh-hant/su/27139/
31,32,無魚，蝦嘛好。,"Bô hî, hê mā hó.",捉不到魚，捉到蝦子也好。比喻退而求其次，聊勝於無。,https://sutian.moe.edu.tw//zh-hant/su/27144/
32,33,無彼號尻川，想欲食彼號瀉藥。,"Bô hit-lō kha-tshng, siūnn-beh tsia̍h hit-lō s...",沒有那種屁股，想吃那種瀉藥。形容人沒有那種能耐，卻妄想做那種事。比喻一個人自不量力。,https://sutian.moe.edu.tw//zh-hant/su/27141/
33,34,無風無搖，倒大樹。,"Bô-hong-bô-iô, tó tuā-tshiū.",沒有絲毫的風，大樹竟然倒了。形容毫無徵兆，發生了意外的大事。,https://sutian.moe.edu.tw//zh-hant/su/28975/
34,35,無日毋知晝，無鬚毋知老。,"Bô ji̍t m̄ tsai tàu, bô tshiu m̄ tsai lāu.",沒出太陽，不知已經到中午了；沒留鬍子，不易察覺人已老邁。比喻光陰易逝，很容易在不知不覺中荒廢。,https://sutian.moe.edu.tw//zh-hant/su/27137/
35,36,無枷夯交椅。,Bô kê giâ kau-í.,沒有枷鎖等刑具可披枷帶鎖，竟然將太師椅扛在身上。比喻自找麻煩，庸人自擾。,https://sutian.moe.edu.tw//zh-hant/su/27142/
36,37,無禁無忌，食百二。,"Bô-kìm-bô-khī, tsia̍h pah-jī.",形容人百無禁忌，毫無忌諱，便能長壽活到一百二十歲。通常是觸碰禁忌者用來自我安慰的說法。,https://sutian.moe.edu.tw//zh-hant/su/27145/
37,38,無毛雞假大格。,Bô môo ke ké tuā-keh.,發育不良羽毛稀疏的雞假冒成體格高大。比喻一個人明明沒錢還裝闊；或指人明明沒有才能，還裝出很有...,https://sutian.moe.edu.tw//zh-hant/su/27138/
38,39,無通生食，哪有通曝乾。,"Bô thang tshenn tsia̍h, ná ū thang pha̍k-kuann.",生吃都不夠，哪能晒成乾？比喻數量不足，不可能有多餘的留下來。也指個人或家計窘困，沒有餘錢作額...,https://sutian.moe.edu.tw//zh-hant/su/27143/
39,40,罔趁較袂散。,Bóng thàn khah bē sàn.,多少賺一點，才不致於陷入窮困。說明即使利潤非常小，也應積極賺取。,https://sutian.moe.edu.tw//zh-hant/su/27037/

In [6]:
# Add columns 
df.insert(4, 'tags', "")
df.insert(4, 'usage', "Proverb")
df

,id,phrases,pronounciation,definition,usage,tags,audiourl
0,1,鴨仔聽雷。,Ah-á thiann luî.,指鴨子聽到雷聲，並不知道是怎麼回事。比喻一個人對所接收的訊息無法理解。比喻一個人對所接收的訊...,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27204/
1,2,愛拚才會贏。,Ài piànn tsiah ē iânn.,要努力才會贏。比喻唯有努力奮鬥，才能克服困難，成就一番事業。,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27161/
2,3,愛媠毋驚流鼻水。,Ài-suí m̄ kiann lâu phīnn-tsuí.,為了展示自己姣好的身材，天氣再冷，寧可挨寒受凍，也不願多穿衣服。常用以揶揄女性愛美，寧可付出...,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27162/
3,4,暗頭仔食西瓜，半暝仔反症。,"Àm-thâu-á tsia̍h si-kue, puànn-mê-á huán-tsìng.",傍晚吃西瓜，半夜症狀急遽變化。指中途變卦，出爾反爾。,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/29615/
4,5,暗頓減食一口，活甲九十九。,"Àm-tǹg kiám tsia̍h tsi̍t kháu, ua̍h kah káu-ts...",晚餐少吃一口，活到九十九。說明晚餐的食用量少一點，有益身體健康。,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27164/
5,6,翁仔某是相欠債。,Ang-á-bóo sī sio-khiàm-tsè.,今世有緣結為夫妻，乃因前世因果，互相欠債所致。夫妻意見不合相互爭吵時，常用這句話來勸雙方姻緣...,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27093/
6,7,翁某若仝心，烏塗變成金。,"Ang-bóo nā kāng-sim, oo-thôo piàn-sîng kim.",夫妻若同心協力，沒有價值的黑土都能變成高價值的東西。比喻夫妻和諧，一起努力，任何事都可成就。,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27094/
7,8,尪姨順話尾，假童害眾人。,"Ang-î sūn uē-bué, ké tâng hāi tsìng-lâng.",靈媒會順著對方的心意說話，假冒之乩童故意裝神弄鬼來欺騙人。此指靈媒、乩童借揣摩情況來決定說話...,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27026/
8,9,翁親某親，老婆仔拋捙輪。,"Ang tshin bóo tshin, lāu-pô-á pha-tshia-lin.",夫妻恩愛，老婆婆翻筋斗也不管。「老婆仔」是指年邁的母親，「拋捙輪」是翻筋斗，這裡指老母親跌倒...,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27095/
9,10,紅媠，烏大範。,"Âng suí, oo tuā-pān.",紅色美麗，黑色大方。形容人衣著色彩，紅色顯得鮮豔亮麗，黑色呈現高貴大方，有氣質、有風味。也可...,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27061/
10,11,肉欲予人食，骨毋予人齧。,"Bah beh hōo lâng tsia̍h, kut m̄ hōo lâng khè.",肉還可以讓人家吃，骨頭千萬不可被人家啃。指被欺負，委曲求全，但忍耐有一定的限度，不能被欺負太...,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/29014/
11,12,䆀猴𠢕欠數。,Bái-kâu gâu khiàm-siàu.,難纏的客人愛賒帳。形容人外型不佳又愛賒帳。,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27217/
12,13,目睭花花，匏仔看做菜瓜。,"Ba̍k-tsiu hue-hue, pû-á khuànn-tsò tshài-kue.",眼睛看不清楚，瓠瓜看成絲瓜。嘲笑別人一時恍神，把形狀相近的物品看成別的東西。,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/26983/
13,14,目睭看懸，無看低。,"Ba̍k-tsiu khuànn-kuân, bô khuànn-kē.",眼睛長在頭頂上，看上不看下。形容人走路不看路。引申為人勢利，看不起身分較低的人。,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/26986/
14,15,目睭看佇粿，跤踏著火。,"Ba̍k-tsiu khuànn tī kué, kha ta̍h-tio̍h hué.",眼睛看著糕品，腳踩到火。用來勸人做事不要只顧當前的好處，而忘了週遭的危險，以免身陷險境而不知。,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/26985/
15,16,目睭金金人傷重。,Ba̍k-tsiu kim-kim lâng siong-tiōng.,眼睛睜大，病情嚴重。形容人病得很嚴重，只能張大眼睛，無法動彈；也用來比喻遇到事情束手無策，只...,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/26984/
16,17,目睭掛斗概，看人物就愛。,"Ba̍k-tsiu kuà táu-kài, khuànn lâng mi̍h tō ài.",眼睛掛著平斗的木概，看到別人的東西就想要。用來形容人過於貪心。以前用「斗」來測量穀物豆類等東...,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/26987/
17,18,慢牛厚屎尿。,Bān gû kāu-sái-jiō.,行動遲緩的牛屎尿多。比喻懶惰的人做事不乾脆，常找藉口逃避或延遲該盡的責任。,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27183/
18,19,萬事起頭難。,Bān-sū khí-thâu lân.,一切事情開頭階段都很困難。意指事情剛開始的時候，都比較困難，只要不放棄，繼續做，久了就會順手...,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27169/
19,20,買賣算分，相請無論。,"Bé-bē sǹg hun, sio-tshiánn bô lūn.",做生意就得把帳目算個清楚，至於請客吃飯，則無需計較。說明生意與交情的界線理應分明。,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27152/
20,21,馬四跤也會著觸。,Bé sì kha iā ē tio̍h-tak.,馬有四條腿，也會因失蹄而跌倒；表示再聰明能幹的人，都會有失意、落魄之時。,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/29027/
21,22,買田愛揀好田底，娶某愛揀好娘嬭。,"Bé tshân ài kíng hó tshân té, tshuā-bóo ài kín...",買田地，要慎選土質好的田地；娶老婆，要先觀察女方母親之行為舉止。意即有其母必有其女，用來說明...,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27150/
22,23,買厝，買厝邊。,"Bé tshù, bé tshù-pinn.",買房子要慎選好鄰居。強調選擇住家時，鄰居的好壞至關重要。,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27151/
23,24,袂曉剃頭，拄著鬍鬚。,"Bē-hiáu thì-thâu, tú-tio̍h hôo-tshiu.",不會理髮，遇到大鬍子。理髮師技術還不夠純熟，首次上場就遇到一個大鬍子的客人，以致於手忙腳亂，...,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27098/
24,25,袂生，牽拖厝邊。,"Bē sinn, khan-thua tshù-pinn.",自己無法生育，卻怪罪鄰居。是用來嘲諷出了問題不自我檢討，卻只會卸責給他人。俗諺多數前後句押韻...,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/29039/
25,26,賣茶講茶芳，賣花講花紅。,"Bē tê kóng tê phang, bē hue kóng hue âng.",賣茶葉的人強調自己賣的茶葉有多香；賣花的人強調自己賣的花顏色有多麼的鮮豔。比喻為了要把自己的...,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27194/
26,27,欲好額等後世，欲做官學做戲。,"Beh hó-gia̍h tán āu-sì, beh tsò-kuann o̍h tsò-hì.",如果想發財就等下輩子，如果想當官，去戲班子演戲就能過乾癮。諷刺人此生再無致富與升官的機會，有...,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27115/
27,28,欲哭無目屎。,Beh khàu bô ba̍k-sái.,想哭卻掉不下淚來。比喻極度哀傷、悲痛。,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/29617/
28,29,欲食胡蠅，家己欱。,"Beh tsia̍h hôo-sîn, ka-kī hap.",想吃蒼蠅得自己去捕捉。引申為凡事得自食其力，不可依賴別人。,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/29064/
29,30,無米有舂臼，無囝抱新婦。,"Bô bí ū tsing-khū, bô kiánn phō sin-pū.",沒有米卻有搗米的臼；沒有兒子領養一個童養媳。形容人只會做白日夢，不切實際。,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27140/
30,31,無牛駛馬。,Bô gû sái bé.,沒有牛只能用馬匹來替代。形容退而求其次，暫且代用的無奈。,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27139/
31,32,無魚，蝦嘛好。,"Bô hî, hê mā hó.",捉不到魚，捉到蝦子也好。比喻退而求其次，聊勝於無。,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27144/
32,33,無彼號尻川，想欲食彼號瀉藥。,"Bô hit-lō kha-tshng, siūnn-beh tsia̍h hit-lō s...",沒有那種屁股，想吃那種瀉藥。形容人沒有那種能耐，卻妄想做那種事。比喻一個人自不量力。,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27141/
33,34,無風無搖，倒大樹。,"Bô-hong-bô-iô, tó tuā-tshiū.",沒有絲毫的風，大樹竟然倒了。形容毫無徵兆，發生了意外的大事。,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/28975/
34,35,無日毋知晝，無鬚毋知老。,"Bô ji̍t m̄ tsai tàu, bô tshiu m̄ tsai lāu.",沒出太陽，不知已經到中午了；沒留鬍子，不易察覺人已老邁。比喻光陰易逝，很容易在不知不覺中荒廢。,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27137/
35,36,無枷夯交椅。,Bô kê giâ kau-í.,沒有枷鎖等刑具可披枷帶鎖，竟然將太師椅扛在身上。比喻自找麻煩，庸人自擾。,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27142/
36,37,無禁無忌，食百二。,"Bô-kìm-bô-khī, tsia̍h pah-jī.",形容人百無禁忌，毫無忌諱，便能長壽活到一百二十歲。通常是觸碰禁忌者用來自我安慰的說法。,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27145/
37,38,無毛雞假大格。,Bô môo ke ké tuā-keh.,發育不良羽毛稀疏的雞假冒成體格高大。比喻一個人明明沒錢還裝闊；或指人明明沒有才能，還裝出很有...,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27138/
38,39,無通生食，哪有通曝乾。,"Bô thang tshenn tsia̍h, ná ū thang pha̍k-kuann.",生吃都不夠，哪能晒成乾？比喻數量不足，不可能有多餘的留下來。也指個人或家計窘困，沒有餘錢作額...,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27143/
39,40,罔趁較袂散。,Bóng thàn khah bē sàn.,多少賺一點，才不致於陷入窮困。說明即使利潤非常小，也應積極賺取。,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27037/

In [7]:
# Loop through the data frame, call API for translation of definition
for i in range(len(df)):
    chinese = df.at[i, 'definition']
    # print(chinese)
    response = requests.post(
        "http://localhost:8000/translate/invoke",
        json = {
            'input': {'Definition' : chinese}}
    )
    translated_def = response.json()['output']['content']
    df.at[i, 'definition'] = translated_def
df

,id,phrases,pronounciation,definition,usage,tags,audiourl
0,1,鴨仔聽雷。,Ah-á thiann luî.,"Refers to a duck hearing thunder, not knowing ...",Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27204/
1,2,愛拚才會贏。,Ài piànn tsiah ē iânn.,You must work hard to win. It's a metaphor tha...,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27161/
2,3,愛媠毋驚流鼻水。,Ài-suí m̄ kiann lâu phīnn-tsuí.,"In order to show off their good figure, no mat...",Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27162/
3,4,暗頭仔食西瓜，半暝仔反症。,"Àm-thâu-á tsia̍h si-kue, puànn-mê-á huán-tsìng.","Eating watermelon in the evening, symptoms dra...",Proverb,,https://sutian.moe.edu.tw//zh-hant/su/29615/
4,5,暗頓減食一口，活甲九十九。,"Àm-tǹg kiám tsia̍h tsi̍t kháu, ua̍h kah káu-ts...","Eating less for dinner, live to ninety-nine. I...",Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27164/
5,6,翁仔某是相欠債。,Ang-á-bóo sī sio-khiàm-tsè.,Being husband and wife in this life is due to ...,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27093/
6,7,翁某若仝心，烏塗變成金。,"Ang-bóo nā kāng-sim, oo-thôo piàn-sîng kim.",When a husband and wife work together in harmo...,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27094/
7,8,尪姨順話尾，假童害眾人。,"Ang-î sūn uē-bué, ké tâng hāi tsìng-lâng.",Mediums speak according to the wishes of other...,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27026/
8,9,翁親某親，老婆仔拋捙輪。,"Ang tshin bóo tshin, lāu-pô-á pha-tshia-lin.","A couple deeply in love, ignoring even if the ...",Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27095/
9,10,紅媠，烏大範。,"Âng suí, oo tuā-pān.","Red is beautiful, black is elegant. It describ...",Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27061/
10,11,肉欲予人食，骨毋予人齧。,"Bah beh hōo lâng tsia̍h, kut m̄ hōo lâng khè.","You can let people eat the meat, but never let...",Proverb,,https://sutian.moe.edu.tw//zh-hant/su/29014/
11,12,䆀猴𠢕欠數。,Bái-kâu gâu khiàm-siàu.,Troublesome customers love to buy on credit. I...,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27217/
12,13,目睭花花，匏仔看做菜瓜。,"Ba̍k-tsiu hue-hue, pû-á khuànn-tsò tshài-kue.","Refers to not seeing clearly, mistaking a bott...",Proverb,,https://sutian.moe.edu.tw//zh-hant/su/26983/
13,14,目睭看懸，無看低。,"Ba̍k-tsiu khuànn-kuân, bô khuànn-kē.","Eyes on top of the head, looking up but not do...",Proverb,,https://sutian.moe.edu.tw//zh-hant/su/26986/
14,15,目睭看佇粿，跤踏著火。,"Ba̍k-tsiu khuànn tī kué, kha ta̍h-tio̍h hué.","Eyes on the cake, feet stepping on fire. Used ...",Proverb,,https://sutian.moe.edu.tw//zh-hant/su/26985/
15,16,目睭金金人傷重。,Ba̍k-tsiu kim-kim lâng siong-tiōng.,"Eyes wide open, the condition is severe. It de...",Proverb,,https://sutian.moe.edu.tw//zh-hant/su/26984/
16,17,目睭掛斗概，看人物就愛。,"Ba̍k-tsiu kuà táu-kài, khuànn lâng mi̍h tō ài.",Eyes with a leveling wood on the measuring buc...,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/26987/
17,18,慢牛厚屎尿。,Bān gû kāu-sái-jiō.,Slow-moving cattle urinate a lot. A metaphor f...,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27183/
18,19,萬事起頭難。,Bān-sū khí-thâu lân.,Everything is difficult at the beginning. It m...,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27169/
19,20,買賣算分，相請無論。,"Bé-bē sǹg hun, sio-tshiánn bô lūn.","In business, it is necessary to keep clear acc...",Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27152/
20,21,馬四跤也會著觸。,Bé sì kha iā ē tio̍h-tak.,Even a horse with four legs will stumble and f...,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/29027/
21,22,買田愛揀好田底，娶某愛揀好娘嬭。,"Bé tshân ài kíng hó tshân té, tshuā-bóo ài kín...","When buying land, choose one with good soil qu...",Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27150/
22,23,買厝，買厝邊。,"Bé tshù, bé tshù-pinn.","When buying a house, it is important to choose...",Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27151/
23,24,袂曉剃頭，拄著鬍鬚。,"Bē-hiáu thì-thâu, tú-tio̍h hôo-tshiu.",Refers to a barber who is not skilled enough a...,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27098/
24,25,袂生，牽拖厝邊。,"Bē sinn, khan-thua tshù-pinn.","Being infertile oneself, yet blaming the neigh...",Proverb,,https://sutian.moe.edu.tw//zh-hant/su/29039/
25,26,賣茶講茶芳，賣花講花紅。,"Bē tê kóng tê phang, bē hue kóng hue âng.",The tea seller emphasizes how fragrant the tea...,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27194/
26,27,欲好額等後世，欲做官學做戲。,"Beh hó-gia̍h tán āu-sì, beh tsò-kuann o̍h tsò-hì.","If you want to get rich, wait for your next li...",Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27115/
27,28,欲哭無目屎。,Beh khàu bô ba̍k-sái.,Wants to cry but can't shed tears. A metaphor ...,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/29617/
28,29,欲食胡蠅，家己欱。,"Beh tsia̍h hôo-sîn, ka-kī hap.","If you want to eat flies, you have to catch th...",Proverb,,https://sutian.moe.edu.tw//zh-hant/su/29064/
29,30,無米有舂臼，無囝抱新婦。,"Bô bí ū tsing-khū, bô kiánn phō sin-pū.",Having a mortar without rice; adopting a daugh...,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27140/
30,31,無牛駛馬。,Bô gû sái bé.,"Without cows, one can only use horses instead....",Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27139/
31,32,無魚，蝦嘛好。,"Bô hî, hê mā hó.",Catching shrimp instead of fish is also good. ...,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27144/
32,33,無彼號尻川，想欲食彼號瀉藥。,"Bô hit-lō kha-tshng, siūnn-beh tsia̍h hit-lō s...","Refers to not having the kind of buttocks, yet...",Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27141/
33,34,無風無搖，倒大樹。,"Bô-hong-bô-iô, tó tuā-tshiū.","There was not the slightest breeze, yet the bi...",Proverb,,https://sutian.moe.edu.tw//zh-hant/su/28975/
34,35,無日毋知晝，無鬚毋知老。,"Bô ji̍t m̄ tsai tàu, bô tshiu m̄ tsai lāu.","Without the sun, one does not realize it is al...",Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27137/
35,36,無枷夯交椅。,Bô kê giâ kau-í.,Without shackles or other torture devices to w...,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27142/
36,37,無禁無忌，食百二。,"Bô-kìm-bô-khī, tsia̍h pah-jī.",Describes a person who lives without any taboo...,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27145/
37,38,無毛雞假大格。,Bô môo ke ké tuā-keh.,Refers to an underdeveloped chicken with spars...,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27138/
38,39,無通生食，哪有通曝乾。,"Bô thang tshenn tsia̍h, ná ū thang pha̍k-kuann.","Eating it raw isn't even enough, how can it be...",Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27143/
39,40,罔趁較袂散。,Bóng thàn khah bē sàn.,Earn a little to avoid falling into poverty. T...,Proverb,,https://sutian.moe.edu.tw//zh-hant/su/27037/

In [8]:
# Loop through the data frame, call API for adding tags
for i in range(len(df)):
    phrase = df.at[i, 'usage'] + ": " + df.at[i, 'phrases']
    # print(phrase)
    
    response = requests.post(
        "http://localhost:8000/categorize/invoke",
        json = {
            'input': {'phrase' : phrase}}
    )
    tags = response.json()['output']['content']
    # print(tags)
    df.at[i, 'tags'] = tags
df

,id,phrases,pronounciation,definition,usage,tags,audiourl
0,1,鴨仔聽雷。,Ah-á thiann luî.,"Refers to a duck hearing thunder, not knowing ...",Proverb,"funny,wisdom",https://sutian.moe.edu.tw//zh-hant/su/27204/
1,2,愛拚才會贏。,Ài piànn tsiah ē iânn.,You must work hard to win. It's a metaphor tha...,Proverb,"perseverance,success",https://sutian.moe.edu.tw//zh-hant/su/27161/
2,3,愛媠毋驚流鼻水。,Ài-suí m̄ kiann lâu phīnn-tsuí.,"In order to show off their good figure, no mat...",Proverb,"funny,wisdom",https://sutian.moe.edu.tw//zh-hant/su/27162/
3,4,暗頭仔食西瓜，半暝仔反症。,"Àm-thâu-á tsia̍h si-kue, puànn-mê-á huán-tsìng.","Eating watermelon in the evening, symptoms dra...",Proverb,"funny,wisdom",https://sutian.moe.edu.tw//zh-hant/su/29615/
4,5,暗頓減食一口，活甲九十九。,"Àm-tǹg kiám tsia̍h tsi̍t kháu, ua̍h kah káu-ts...","Eating less for dinner, live to ninety-nine. I...",Proverb,wisdom,https://sutian.moe.edu.tw//zh-hant/su/27164/
5,6,翁仔某是相欠債。,Ang-á-bóo sī sio-khiàm-tsè.,Being husband and wife in this life is due to ...,Proverb,"relationships,wisdom",https://sutian.moe.edu.tw//zh-hant/su/27093/
6,7,翁某若仝心，烏塗變成金。,"Ang-bóo nā kāng-sim, oo-thôo piàn-sîng kim.",When a husband and wife work together in harmo...,Proverb,"relationships,wisdom",https://sutian.moe.edu.tw//zh-hant/su/27094/
7,8,尪姨順話尾，假童害眾人。,"Ang-î sūn uē-bué, ké tâng hāi tsìng-lâng.",Mediums speak according to the wishes of other...,Proverb,wisdom,https://sutian.moe.edu.tw//zh-hant/su/27026/
8,9,翁親某親，老婆仔拋捙輪。,"Ang tshin bóo tshin, lāu-pô-á pha-tshia-lin.","A couple deeply in love, ignoring even if the ...",Proverb,"relationships,wisdom",https://sutian.moe.edu.tw//zh-hant/su/27095/
9,10,紅媠，烏大範。,"Âng suí, oo tuā-pān.","Red is beautiful, black is elegant. It describ...",Proverb,wisdom,https://sutian.moe.edu.tw//zh-hant/su/27061/
10,11,肉欲予人食，骨毋予人齧。,"Bah beh hōo lâng tsia̍h, kut m̄ hōo lâng khè.","You can let people eat the meat, but never let...",Proverb,"wisdom,relationships",https://sutian.moe.edu.tw//zh-hant/su/29014/
11,12,䆀猴𠢕欠數。,Bái-kâu gâu khiàm-siàu.,Troublesome customers love to buy on credit. I...,Proverb,"wisdom,funny",https://sutian.moe.edu.tw//zh-hant/su/27217/
12,13,目睭花花，匏仔看做菜瓜。,"Ba̍k-tsiu hue-hue, pû-á khuànn-tsò tshài-kue.","Refers to not seeing clearly, mistaking a bott...",Proverb,"funny,wisdom",https://sutian.moe.edu.tw//zh-hant/su/26983/
13,14,目睭看懸，無看低。,"Ba̍k-tsiu khuànn-kuân, bô khuànn-kē.","Eyes on top of the head, looking up but not do...",Proverb,wisdom,https://sutian.moe.edu.tw//zh-hant/su/26986/
14,15,目睭看佇粿，跤踏著火。,"Ba̍k-tsiu khuànn tī kué, kha ta̍h-tio̍h hué.","Eyes on the cake, feet stepping on fire. Used ...",Proverb,"wisdom,hardship",https://sutian.moe.edu.tw//zh-hant/su/26985/
15,16,目睭金金人傷重。,Ba̍k-tsiu kim-kim lâng siong-tiōng.,"Eyes wide open, the condition is severe. It de...",Proverb,"wisdom,hardship",https://sutian.moe.edu.tw//zh-hant/su/26984/
16,17,目睭掛斗概，看人物就愛。,"Ba̍k-tsiu kuà táu-kài, khuànn lâng mi̍h tō ài.",Eyes with a leveling wood on the measuring buc...,Proverb,"wisdom,relationships",https://sutian.moe.edu.tw//zh-hant/su/26987/
17,18,慢牛厚屎尿。,Bān gû kāu-sái-jiō.,Slow-moving cattle urinate a lot. A metaphor f...,Proverb,"wisdom, perseverance",https://sutian.moe.edu.tw//zh-hant/su/27183/
18,19,萬事起頭難。,Bān-sū khí-thâu lân.,Everything is difficult at the beginning. It m...,Proverb,"wisdom,perseverance",https://sutian.moe.edu.tw//zh-hant/su/27169/
19,20,買賣算分，相請無論。,"Bé-bē sǹg hun, sio-tshiánn bô lūn.","In business, it is necessary to keep clear acc...",Proverb,"wisdom,relationships",https://sutian.moe.edu.tw//zh-hant/su/27152/
20,21,馬四跤也會著觸。,Bé sì kha iā ē tio̍h-tak.,Even a horse with four legs will stumble and f...,Proverb,"wisdom, perseverance",https://sutian.moe.edu.tw//zh-hant/su/29027/
21,22,買田愛揀好田底，娶某愛揀好娘嬭。,"Bé tshân ài kíng hó tshân té, tshuā-bóo ài kín...","When buying land, choose one with good soil qu...",Proverb,"wisdom,relationships",https://sutian.moe.edu.tw//zh-hant/su/27150/
22,23,買厝，買厝邊。,"Bé tshù, bé tshù-pinn.","When buying a house, it is important to choose...",Proverb,"wisdom,relationships",https://sutian.moe.edu.tw//zh-hant/su/27151/
23,24,袂曉剃頭，拄著鬍鬚。,"Bē-hiáu thì-thâu, tú-tio̍h hôo-tshiu.",Refers to a barber who is not skilled enough a...,Proverb,wisdom,https://sutian.moe.edu.tw//zh-hant/su/27098/
24,25,袂生，牽拖厝邊。,"Bē sinn, khan-thua tshù-pinn.","Being infertile oneself, yet blaming the neigh...",Proverb,"relationships,wisdom",https://sutian.moe.edu.tw//zh-hant/su/29039/
25,26,賣茶講茶芳，賣花講花紅。,"Bē tê kóng tê phang, bē hue kóng hue âng.",The tea seller emphasizes how fragrant the tea...,Proverb,wisdom,https://sutian.moe.edu.tw//zh-hant/su/27194/
26,27,欲好額等後世，欲做官學做戲。,"Beh hó-gia̍h tán āu-sì, beh tsò-kuann o̍h tsò-hì.","If you want to get rich, wait for your next li...",Proverb,"wisdom,funny",https://sutian.moe.edu.tw//zh-hant/su/27115/
27,28,欲哭無目屎。,Beh khàu bô ba̍k-sái.,Wants to cry but can't shed tears. A metaphor ...,Proverb,"funny,wisdom",https://sutian.moe.edu.tw//zh-hant/su/29617/
28,29,欲食胡蠅，家己欱。,"Beh tsia̍h hôo-sîn, ka-kī hap.","If you want to eat flies, you have to catch th...",Proverb,wisdom,https://sutian.moe.edu.tw//zh-hant/su/29064/
29,30,無米有舂臼，無囝抱新婦。,"Bô bí ū tsing-khū, bô kiánn phō sin-pū.",Having a mortar without rice; adopting a daugh...,Proverb,"relationships,wisdom",https://sutian.moe.edu.tw//zh-hant/su/27140/
30,31,無牛駛馬。,Bô gû sái bé.,"Without cows, one can only use horses instead....",Proverb,wisdom,https://sutian.moe.edu.tw//zh-hant/su/27139/
31,32,無魚，蝦嘛好。,"Bô hî, hê mā hó.",Catching shrimp instead of fish is also good. ...,Proverb,"wisdom,hardship",https://sutian.moe.edu.tw//zh-hant/su/27144/
32,33,無彼號尻川，想欲食彼號瀉藥。,"Bô hit-lō kha-tshng, siūnn-beh tsia̍h hit-lō s...","Refers to not having the kind of buttocks, yet...",Proverb,wisdom,https://sutian.moe.edu.tw//zh-hant/su/27141/
33,34,無風無搖，倒大樹。,"Bô-hong-bô-iô, tó tuā-tshiū.","There was not the slightest breeze, yet the bi...",Proverb,"wisdom,hardship",https://sutian.moe.edu.tw//zh-hant/su/28975/
34,35,無日毋知晝，無鬚毋知老。,"Bô ji̍t m̄ tsai tàu, bô tshiu m̄ tsai lāu.","Without the sun, one does not realize it is al...",Proverb,wisdom,https://sutian.moe.edu.tw//zh-hant/su/27137/
35,36,無枷夯交椅。,Bô kê giâ kau-í.,Without shackles or other torture devices to w...,Proverb,wisdom,https://sutian.moe.edu.tw//zh-hant/su/27142/
36,37,無禁無忌，食百二。,"Bô-kìm-bô-khī, tsia̍h pah-jī.",Describes a person who lives without any taboo...,Proverb,wisdom,https://sutian.moe.edu.tw//zh-hant/su/27145/
37,38,無毛雞假大格。,Bô môo ke ké tuā-keh.,Refers to an underdeveloped chicken with spars...,Proverb,"funny,wisdom",https://sutian.moe.edu.tw//zh-hant/su/27138/
38,39,無通生食，哪有通曝乾。,"Bô thang tshenn tsia̍h, ná ū thang pha̍k-kuann.","Eating it raw isn't even enough, how can it be...",Proverb,"wisdom,hardship",https://sutian.moe.edu.tw//zh-hant/su/27143/
39,40,罔趁較袂散。,Bóng thàn khah bē sàn.,Earn a little to avoid falling into poverty. T...,Proverb,"relationships,wisdom",https://sutian.moe.edu.tw//zh-hant/su/27037/

In [9]:
# Add a mandarin column
df.insert(3, "mandarin", "")
df

,id,phrases,pronounciation,mandarin,definition,usage,tags,audiourl
0,1,鴨仔聽雷。,Ah-á thiann luî.,,"Refers to a duck hearing thunder, not knowing ...",Proverb,"funny,wisdom",https://sutian.moe.edu.tw//zh-hant/su/27204/
1,2,愛拚才會贏。,Ài piànn tsiah ē iânn.,,You must work hard to win. It's a metaphor tha...,Proverb,"perseverance,success",https://sutian.moe.edu.tw//zh-hant/su/27161/
2,3,愛媠毋驚流鼻水。,Ài-suí m̄ kiann lâu phīnn-tsuí.,,"In order to show off their good figure, no mat...",Proverb,"funny,wisdom",https://sutian.moe.edu.tw//zh-hant/su/27162/
3,4,暗頭仔食西瓜，半暝仔反症。,"Àm-thâu-á tsia̍h si-kue, puànn-mê-á huán-tsìng.",,"Eating watermelon in the evening, symptoms dra...",Proverb,"funny,wisdom",https://sutian.moe.edu.tw//zh-hant/su/29615/
4,5,暗頓減食一口，活甲九十九。,"Àm-tǹg kiám tsia̍h tsi̍t kháu, ua̍h kah káu-ts...",,"Eating less for dinner, live to ninety-nine. I...",Proverb,wisdom,https://sutian.moe.edu.tw//zh-hant/su/27164/
5,6,翁仔某是相欠債。,Ang-á-bóo sī sio-khiàm-tsè.,,Being husband and wife in this life is due to ...,Proverb,"relationships,wisdom",https://sutian.moe.edu.tw//zh-hant/su/27093/
6,7,翁某若仝心，烏塗變成金。,"Ang-bóo nā kāng-sim, oo-thôo piàn-sîng kim.",,When a husband and wife work together in harmo...,Proverb,"relationships,wisdom",https://sutian.moe.edu.tw//zh-hant/su/27094/
7,8,尪姨順話尾，假童害眾人。,"Ang-î sūn uē-bué, ké tâng hāi tsìng-lâng.",,Mediums speak according to the wishes of other...,Proverb,wisdom,https://sutian.moe.edu.tw//zh-hant/su/27026/
8,9,翁親某親，老婆仔拋捙輪。,"Ang tshin bóo tshin, lāu-pô-á pha-tshia-lin.",,"A couple deeply in love, ignoring even if the ...",Proverb,"relationships,wisdom",https://sutian.moe.edu.tw//zh-hant/su/27095/
9,10,紅媠，烏大範。,"Âng suí, oo tuā-pān.",,"Red is beautiful, black is elegant. It describ...",Proverb,wisdom,https://sutian.moe.edu.tw//zh-hant/su/27061/
10,11,肉欲予人食，骨毋予人齧。,"Bah beh hōo lâng tsia̍h, kut m̄ hōo lâng khè.",,"You can let people eat the meat, but never let...",Proverb,"wisdom,relationships",https://sutian.moe.edu.tw//zh-hant/su/29014/
11,12,䆀猴𠢕欠數。,Bái-kâu gâu khiàm-siàu.,,Troublesome customers love to buy on credit. I...,Proverb,"wisdom,funny",https://sutian.moe.edu.tw//zh-hant/su/27217/
12,13,目睭花花，匏仔看做菜瓜。,"Ba̍k-tsiu hue-hue, pû-á khuànn-tsò tshài-kue.",,"Refers to not seeing clearly, mistaking a bott...",Proverb,"funny,wisdom",https://sutian.moe.edu.tw//zh-hant/su/26983/
13,14,目睭看懸，無看低。,"Ba̍k-tsiu khuànn-kuân, bô khuànn-kē.",,"Eyes on top of the head, looking up but not do...",Proverb,wisdom,https://sutian.moe.edu.tw//zh-hant/su/26986/
14,15,目睭看佇粿，跤踏著火。,"Ba̍k-tsiu khuànn tī kué, kha ta̍h-tio̍h hué.",,"Eyes on the cake, feet stepping on fire. Used ...",Proverb,"wisdom,hardship",https://sutian.moe.edu.tw//zh-hant/su/26985/
15,16,目睭金金人傷重。,Ba̍k-tsiu kim-kim lâng siong-tiōng.,,"Eyes wide open, the condition is severe. It de...",Proverb,"wisdom,hardship",https://sutian.moe.edu.tw//zh-hant/su/26984/
16,17,目睭掛斗概，看人物就愛。,"Ba̍k-tsiu kuà táu-kài, khuànn lâng mi̍h tō ài.",,Eyes with a leveling wood on the measuring buc...,Proverb,"wisdom,relationships",https://sutian.moe.edu.tw//zh-hant/su/26987/
17,18,慢牛厚屎尿。,Bān gû kāu-sái-jiō.,,Slow-moving cattle urinate a lot. A metaphor f...,Proverb,"wisdom, perseverance",https://sutian.moe.edu.tw//zh-hant/su/27183/
18,19,萬事起頭難。,Bān-sū khí-thâu lân.,,Everything is difficult at the beginning. It m...,Proverb,"wisdom,perseverance",https://sutian.moe.edu.tw//zh-hant/su/27169/
19,20,買賣算分，相請無論。,"Bé-bē sǹg hun, sio-tshiánn bô lūn.",,"In business, it is necessary to keep clear acc...",Proverb,"wisdom,relationships",https://sutian.moe.edu.tw//zh-hant/su/27152/
20,21,馬四跤也會著觸。,Bé sì kha iā ē tio̍h-tak.,,Even a horse with four legs will stumble and f...,Proverb,"wisdom, perseverance",https://sutian.moe.edu.tw//zh-hant/su/29027/
21,22,買田愛揀好田底，娶某愛揀好娘嬭。,"Bé tshân ài kíng hó tshân té, tshuā-bóo ài kín...",,"When buying land, choose one with good soil qu...",Proverb,"wisdom,relationships",https://sutian.moe.edu.tw//zh-hant/su/27150/
22,23,買厝，買厝邊。,"Bé tshù, bé tshù-pinn.",,"When buying a house, it is important to choose...",Proverb,"wisdom,relationships",https://sutian.moe.edu.tw//zh-hant/su/27151/
23,24,袂曉剃頭，拄著鬍鬚。,"Bē-hiáu thì-thâu, tú-tio̍h hôo-tshiu.",,Refers to a barber who is not skilled enough a...,Proverb,wisdom,https://sutian.moe.edu.tw//zh-hant/su/27098/
24,25,袂生，牽拖厝邊。,"Bē sinn, khan-thua tshù-pinn.",,"Being infertile oneself, yet blaming the neigh...",Proverb,"relationships,wisdom",https://sutian.moe.edu.tw//zh-hant/su/29039/
25,26,賣茶講茶芳，賣花講花紅。,"Bē tê kóng tê phang, bē hue kóng hue âng.",,The tea seller emphasizes how fragrant the tea...,Proverb,wisdom,https://sutian.moe.edu.tw//zh-hant/su/27194/
26,27,欲好額等後世，欲做官學做戲。,"Beh hó-gia̍h tán āu-sì, beh tsò-kuann o̍h tsò-hì.",,"If you want to get rich, wait for your next li...",Proverb,"wisdom,funny",https://sutian.moe.edu.tw//zh-hant/su/27115/
27,28,欲哭無目屎。,Beh khàu bô ba̍k-sái.,,Wants to cry but can't shed tears. A metaphor ...,Proverb,"funny,wisdom",https://sutian.moe.edu.tw//zh-hant/su/29617/
28,29,欲食胡蠅，家己欱。,"Beh tsia̍h hôo-sîn, ka-kī hap.",,"If you want to eat flies, you have to catch th...",Proverb,wisdom,https://sutian.moe.edu.tw//zh-hant/su/29064/
29,30,無米有舂臼，無囝抱新婦。,"Bô bí ū tsing-khū, bô kiánn phō sin-pū.",,Having a mortar without rice; adopting a daugh...,Proverb,"relationships,wisdom",https://sutian.moe.edu.tw//zh-hant/su/27140/
30,31,無牛駛馬。,Bô gû sái bé.,,"Without cows, one can only use horses instead....",Proverb,wisdom,https://sutian.moe.edu.tw//zh-hant/su/27139/
31,32,無魚，蝦嘛好。,"Bô hî, hê mā hó.",,Catching shrimp instead of fish is also good. ...,Proverb,"wisdom,hardship",https://sutian.moe.edu.tw//zh-hant/su/27144/
32,33,無彼號尻川，想欲食彼號瀉藥。,"Bô hit-lō kha-tshng, siūnn-beh tsia̍h hit-lō s...",,"Refers to not having the kind of buttocks, yet...",Proverb,wisdom,https://sutian.moe.edu.tw//zh-hant/su/27141/
33,34,無風無搖，倒大樹。,"Bô-hong-bô-iô, tó tuā-tshiū.",,"There was not the slightest breeze, yet the bi...",Proverb,"wisdom,hardship",https://sutian.moe.edu.tw//zh-hant/su/28975/
34,35,無日毋知晝，無鬚毋知老。,"Bô ji̍t m̄ tsai tàu, bô tshiu m̄ tsai lāu.",,"Without the sun, one does not realize it is al...",Proverb,wisdom,https://sutian.moe.edu.tw//zh-hant/su/27137/
35,36,無枷夯交椅。,Bô kê giâ kau-í.,,Without shackles or other torture devices to w...,Proverb,wisdom,https://sutian.moe.edu.tw//zh-hant/su/27142/
36,37,無禁無忌，食百二。,"Bô-kìm-bô-khī, tsia̍h pah-jī.",,Describes a person who lives without any taboo...,Proverb,wisdom,https://sutian.moe.edu.tw//zh-hant/su/27145/
37,38,無毛雞假大格。,Bô môo ke ké tuā-keh.,,Refers to an underdeveloped chicken with spars...,Proverb,"funny,wisdom",https://sutian.moe.edu.tw//zh-hant/su/27138/
38,39,無通生食，哪有通曝乾。,"Bô thang tshenn tsia̍h, ná ū thang pha̍k-kuann.",,"Eating it raw isn't even enough, how can it be...",Proverb,"wisdom,hardship",https://sutian.moe.edu.tw//zh-hant/su/27143/
39,40,罔趁較袂散。,Bóng thàn khah bē sàn.,,Earn a little to avoid falling into poverty. T...,Proverb,"relationships,wisdom",https://sutian.moe.edu.tw//zh-hant/su/27037/

In [16]:
# Add mandarin translation 
for i in range(len(df)):
    phrase = df.at[i, 'phrases']
    definition = df.at[i, 'definition']
    response = requests.post(
        "http://localhost:8000/translate-to-mandarin/invoke",
        json = {
            'input': {'phrase' : phrase, 'definition': definition}}
    )
    df.at[i, 'mandarin'] = response.json()['output']['content']

df

KeyboardInterrupt:

In [15]:
# format the tag to import to psql column text[]
# 8/8 這邊要改 tags的格式
for i in range(len(df)):
    tags_string = df.at[i, "tags"]
    tags_array = tags_string.split(",")
    new_tags_string = "\"{"
    for j in range(len(tags_array)):
        tags_array[j] = tags_array[j].lstrip(' ')
        new_tags_string += tags_array[j] + ","
    tags_string = new_tags_string[:-1] + "}\""
    df.at[i, "tags"] = tags_string

df

,id,phrases,pronounciation,mandarin,definition,usage,tags,audiourl
0,1,鴨仔聽雷。,Ah-á thiann luî.,鴨子聽雷,"Refers to a duck hearing thunder, not knowing ...",Proverb,"{{""{""{funny,wisdom}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/27204/
1,2,愛拚才會贏。,Ài piànn tsiah ē iânn.,愛拼才會贏,You must work hard to win. It's a metaphor tha...,Proverb,"{{""{""{perseverance,success}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/27161/
2,3,愛媠毋驚流鼻水。,Ài-suí m̄ kiann lâu phīnn-tsuí.,愛美不怕冷，寧願凍著也不穿多。,"In order to show off their good figure, no mat...",Proverb,"{{""{""{funny,wisdom}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/27162/
3,4,暗頭仔食西瓜，半暝仔反症。,"Àm-thâu-á tsia̍h si-kue, puànn-mê-á huán-tsìng.",晚上吃西瓜，半夜症狀大變。,"Eating watermelon in the evening, symptoms dra...",Proverb,"{{""{""{funny,wisdom}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/29615/
4,5,暗頓減食一口，活甲九十九。,"Àm-tǹg kiám tsia̍h tsi̍t kháu, ua̍h kah káu-ts...",晚餐少吃一口，活到九十九。,"Eating less for dinner, live to ninety-nine. I...",Proverb,"{{""{""{wisdom}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/27164/
5,6,翁仔某是相欠債。,Ang-á-bóo sī sio-khiàm-tsè.,夫妻本是前世的債务,Being husband and wife in this life is due to ...,Proverb,"{{""{""{relationships,wisdom}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/27093/
6,7,翁某若仝心，烏塗變成金。,"Ang-bóo nā kāng-sim, oo-thôo piàn-sîng kim.",夫妻若同心，黑土也能變成金。,When a husband and wife work together in harmo...,Proverb,"{{""{""{relationships,wisdom}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/27094/
7,8,尪姨順話尾，假童害眾人。,"Ang-î sūn uē-bué, ké tâng hāi tsìng-lâng.",巫媒順著人意說話，假的巫師裝神弄鬼欺騙眾人。,Mediums speak according to the wishes of other...,Proverb,"{{""{""{wisdom}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/27026/
8,9,翁親某親，老婆仔拋捙輪。,"Ang tshin bóo tshin, lāu-pô-á pha-tshia-lin.",夫妻親熱，連老母親翻跟斗也不顧。,"A couple deeply in love, ignoring even if the ...",Proverb,"{{""{""{relationships,wisdom}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/27095/
9,10,紅媠，烏大範。,"Âng suí, oo tuā-pān.",紅美，烏大方。,"Red is beautiful, black is elegant. It describ...",Proverb,"{{""{""{wisdom}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/27061/
10,11,肉欲予人食，骨毋予人齧。,"Bah beh hōo lâng tsia̍h, kut m̄ hōo lâng khè.",你可以讓人吃肉，但切勿讓人啃骨。,"You can let people eat the meat, but never let...",Proverb,"{{""{""{wisdom,relationships}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/29014/
11,12,䆀猴𠢕欠數。,Bái-kâu gâu khiàm-siàu.,麻煩的客戶喜歡賒帳。,Troublesome customers love to buy on credit. I...,Proverb,"{{""{""{wisdom,funny}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/27217/
12,13,目睭花花，匏仔看做菜瓜。,"Ba̍k-tsiu hue-hue, pû-á khuànn-tsò tshài-kue.",目睭花花，瓢仔看做絲瓜。,"Refers to not seeing clearly, mistaking a bott...",Proverb,"{{""{""{funny,wisdom}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/26983/
13,14,目睭看懸，無看低。,"Ba̍k-tsiu khuànn-kuân, bô khuànn-kē.",目睭望懸，無看低,"Eyes on top of the head, looking up but not do...",Proverb,"{{""{""{wisdom}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/26986/
14,15,目睭看佇粿，跤踏著火。,"Ba̍k-tsiu khuànn tī kué, kha ta̍h-tio̍h hué.",目睛看著糕點，腳踩在火上。,"Eyes on the cake, feet stepping on fire. Used ...",Proverb,"{{""{""{wisdom,hardship}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/26985/
15,16,目睭金金人傷重。,Ba̍k-tsiu kim-kim lâng siong-tiōng.,目睛睜大，情況嚴重。,"Eyes wide open, the condition is severe. It de...",Proverb,"{{""{""{wisdom,hardship}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/26984/
16,17,目睭掛斗概，看人物就愛。,"Ba̍k-tsiu kuà táu-kài, khuànn lâng mi̍h tō ài.",目睭掛鬥概，看人物就愛。,Eyes with a leveling wood on the measuring buc...,Proverb,"{{""{""{wisdom,relationships}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/26987/
17,18,慢牛厚屎尿。,Bān gû kāu-sái-jiō.,慢牛厚糞尿,Slow-moving cattle urinate a lot. A metaphor f...,Proverb,"{{""{""{wisdom,perseverance}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/27183/
18,19,萬事起頭難。,Bān-sū khí-thâu lân.,萬事起頭難。,Everything is difficult at the beginning. It m...,Proverb,"{{""{""{wisdom,perseverance}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/27169/
19,20,買賣算分，相請無論。,"Bé-bē sǹg hun, sio-tshiánn bô lūn.",買賣要算清楚，款待則無需計較。,"In business, it is necessary to keep clear acc...",Proverb,"{{""{""{wisdom,relationships}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/27152/
20,21,馬四跤也會著觸。,Bé sì kha iā ē tio̍h-tak.,即使是四條腿的馬，失去一隻蹄子也會跌倒。,Even a horse with four legs will stumble and f...,Proverb,"{{""{""{wisdom,perseverance}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/29027/
21,22,買田愛揀好田底，娶某愛揀好娘嬭。,"Bé tshân ài kíng hó tshân té, tshuā-bóo ài kín...",買田要選好土壤，娶妻要看好婆娘的行為。,"When buying land, choose one with good soil qu...",Proverb,"{{""{""{wisdom,relationships}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/27150/
22,23,買厝，買厝邊。,"Bé tshù, bé tshù-pinn.",買房子，要看鄰居好不好。,"When buying a house, it is important to choose...",Proverb,"{{""{""{wisdom,relationships}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/27151/
23,24,袂曉剃頭，拄著鬍鬚。,"Bē-hiáu thì-thâu, tú-tio̍h hôo-tshiu.",不會剃頭，碰到大鬍子。,Refers to a barber who is not skilled enough a...,Proverb,"{{""{""{wisdom}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/27098/
24,25,袂生，牽拖厝邊。,"Bē sinn, khan-thua tshù-pinn.",自己不孕，卻怪鄰家。,"Being infertile oneself, yet blaming the neigh...",Proverb,"{{""{""{relationships,wisdom}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/29039/
25,26,賣茶講茶芳，賣花講花紅。,"Bē tê kóng tê phang, bē hue kóng hue âng.",賣茶講茶香，賣花講花紅。,The tea seller emphasizes how fragrant the tea...,Proverb,"{{""{""{wisdom}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/27194/
26,27,欲好額等後世，欲做官學做戲。,"Beh hó-gia̍h tán āu-sì, beh tsò-kuann o̍h tsò-hì.",如果想要發財，就等下輩子；如果想當官，參加戲劇團體演戲就可以滿足你的願望。,"If you want to get rich, wait for your next li...",Proverb,"{{""{""{wisdom,funny}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/27115/
27,28,欲哭無目屎。,Beh khàu bô ba̍k-sái.,欲哭無淚,Wants to cry but can't shed tears. A metaphor ...,Proverb,"{{""{""{funny,wisdom}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/29617/
28,29,欲食胡蠅，家己欱。,"Beh tsia̍h hôo-sîn, ka-kī hap.",若想吃蒼蠅，得自己去抓。,"If you want to eat flies, you have to catch th...",Proverb,"{{""{""{wisdom}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/29064/
29,30,無米有舂臼，無囝抱新婦。,"Bô bí ū tsing-khū, bô kiánn phō sin-pū.",無米而有舂臼，無子而抱新婦。,Having a mortar without rice; adopting a daugh...,Proverb,"{{""{""{relationships,wisdom}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/27140/
30,31,無牛駛馬。,Bô gû sái bé.,無牛只好騎馬。,"Without cows, one can only use horses instead....",Proverb,"{{""{""{wisdom}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/27139/
31,32,無魚，蝦嘛好。,"Bô hî, hê mā hó.",沒有魚，蝦也好。,Catching shrimp instead of fish is also good. ...,Proverb,"{{""{""{wisdom,hardship}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/27144/
32,33,無彼號尻川，想欲食彼號瀉藥。,"Bô hit-lō kha-tshng, siūnn-beh tsia̍h hit-lō s...",沒有那種屁股，卻想要吃那種瀉藥。,"Refers to not having the kind of buttocks, yet...",Proverb,"{{""{""{wisdom}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/27141/
33,34,無風無搖，倒大樹。,"Bô-hong-bô-iô, tó tuā-tshiū.",無風無搖，倒大樹。,"There was not the slightest breeze, yet the bi...",Proverb,"{{""{""{wisdom,hardship}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/28975/
34,35,無日毋知晝，無鬚毋知老。,"Bô ji̍t m̄ tsai tàu, bô tshiu m̄ tsai lāu.",無日不知晝，無鬚不知老。,"Without the sun, one does not realize it is al...",Proverb,"{{""{""{wisdom}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/27137/
35,36,無枷夯交椅。,Bô kê giâ kau-í.,無枷無鎖，反背交椅。,Without shackles or other torture devices to w...,Proverb,"{{""{""{wisdom}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/27142/
36,37,無禁無忌，食百二。,"Bô-kìm-bô-khī, tsia̍h pah-jī.",無忌無禁，活到一百二十歲,Describes a person who lives without any taboo...,Proverb,"{{""{""{wisdom}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/27145/
37,38,無毛雞假大格。,Bô môo ke ké tuā-keh.,無毛雞裝大個,Refers to an underdeveloped chicken with spars...,Proverb,"{{""{""{funny,wisdom}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/27138/
38,39,無通生食，哪有通曝乾。,"Bô thang tshenn tsia̍h, ná ū thang pha̍k-kuann.",無通生食，哪有通曝乾。,"Eating it raw isn't even enough, how can it be...",Proverb,"{{""{""{wisdom,hardship}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/27143/
39,40,罔趁較袂散。,Bóng thàn khah bē sàn.,賺一點以免陷入貧窮。即使利潤很少，也應積極賺取。,Earn a little to avoid falling into poverty. T...,Proverb,"{{""{""{relationships,wisdom}""}""}}",https://sutian.moe.edu.tw//zh-hant/su/27037/

In [13]:
df.to_csv('/Users/yushanlu/Desktop/yushan-says/backend/script/data.csv', sep='|', index=False)